### ISSUE TITLE
How to bundle JRE into app?

### ISSUE THREAD

**Issue by Randyshu2018** [wuruoyun/electron-vue-spring#2]
I'm confused with build-in jre

**Comment by JaviOverflow** [comment]
I'm also interested on this!

**Comment by wuruoyun** [comment]
You may use the "extraResources" in Electron Builder configuration to include the JRE into your installer. The "extraResources" files will be copied into "resources" folder of the app's installation folder. In your Electron index.js you can use app.getAppPath() to get the absolute path to the "resources" folder, and the path to your JRE can be build from there.
