### ISSUE TITLE
May I Share a New Project Based on Your Creation?

### ISSUE THREAD

**Issue by leejaesup** [wuruoyun/electron-vue-spring#47]
Hello,

I've been using your project for my studies and find it extremely helpful. I'm planning to create a new project and share it on GitHub. I've checked the license, which allows for replication, but I wanted to ask for your permission before proceeding.

I appreciate your work and believe sharing my project would contribute to the open-source community. Please let me know if you grant me permission.

Thank you

**Comment by wuruoyun** [comment]
Sure! Glad that you find it helpful! Please feel free to go ahead!
